### ISSUE TITLE
Refactorisation par rapport à jslint

### ISSUE THREAD

**Issue by suipotryot** [suipotryot/drawashape#1]
Parce que c'était codé avec les pieds

**Comment by fhgbaguidi** [comment]
Plus qu'une erreur JSLINT =>  
Missing 'use strict' statement. var COLOR = 0xffffff,

Mais on ne peut pas utiliser le mode strict pour le moment. Juste après son activation l'object scene est inaccessible de l'extérieur. Il va falloir qu'on trouve une solution pour cela avant de passer en strict. 
@suipotryot : A toi de voir si on ferme le ticket ou pas.
